# Generated by Django 3.0.5 on 2020-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200810_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=122),
            preserve_default=False,
        ),
    ]
