# Generated by Django 3.0.5 on 2020-08-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.IntegerField(default=None),
        ),
    ]
